spring:
  application:
    name: obsidian-publisher

api:
  base:
    path: /api

obsidian:
  vault:
    path: /home/fenya/obsidian/obsidian

notes:
  ignored:
    directories:
      - templates
  startNote: "index"
  htmlConverted:
    path: "${user.dir}/html"
  attachments:
    path: "${user.dir}/attachments"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics